/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package Ejercicio02_Propuesto;

import Arbol.Arbol;
import javax.swing.DefaultListModel;
import javax.swing.JOptionPane;

/**
 *
 * @author USER
 */
public class FrmEjercicio02 extends javax.swing.JFrame {

    DefaultListModel postOrden = new DefaultListModel();
    DefaultListModel preOrden = new DefaultListModel();
    DefaultListModel enOrden = new DefaultListModel();
    Arbol<Integer> lista = new Arbol<>();
    
    public FrmEjercicio02() {
        initComponents();
        lstPreorden.setModel(preOrden);
        lstPostorden.setModel(postOrden);
        lstEnorden.setModel(enOrden);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        bg = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        txtValor = new javax.swing.JTextField();
        btnAgregar = new javax.swing.JButton();
        jScrollPane1 = new javax.swing.JScrollPane();
        lstPreorden = new javax.swing.JList<>();
        jScrollPane2 = new javax.swing.JScrollPane();
        lstEnorden = new javax.swing.JList<>();
        jScrollPane3 = new javax.swing.JScrollPane();
        lstPostorden = new javax.swing.JList<>();
        btnSumar = new javax.swing.JButton();
        btnNumeroHojas = new javax.swing.JButton();
        btnProfundidad = new javax.swing.JButton();
        btnResultados = new javax.swing.JButton();
        jScrollPane4 = new javax.swing.JScrollPane();
        txaBotones = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        bg.setBackground(new java.awt.Color(255, 255, 255));

        jLabel1.setFont(new java.awt.Font("Segoe UI Emoji", 1, 24)); // NOI18N
        jLabel1.setText("ARBOL BINARIO DE ENTEROS");

        jLabel2.setFont(new java.awt.Font("Segoe UI Emoji", 0, 14)); // NOI18N
        jLabel2.setText("Valor:");

        btnAgregar.setText("AGREGAR");
        btnAgregar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAgregarActionPerformed(evt);
            }
        });

        lstPreorden.setBorder(javax.swing.BorderFactory.createTitledBorder("PREORDEN:"));
        jScrollPane1.setViewportView(lstPreorden);

        lstEnorden.setBorder(javax.swing.BorderFactory.createTitledBorder("ENORDEN:"));
        jScrollPane2.setViewportView(lstEnorden);

        lstPostorden.setBorder(javax.swing.BorderFactory.createTitledBorder("POSTORDEN:"));
        jScrollPane3.setViewportView(lstPostorden);

        btnSumar.setText("SUMAR");
        btnSumar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSumarActionPerformed(evt);
            }
        });

        btnNumeroHojas.setText("N° HOJAS");
        btnNumeroHojas.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnNumeroHojasActionPerformed(evt);
            }
        });

        btnProfundidad.setText("PROFUNDIDAD");
        btnProfundidad.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnProfundidadActionPerformed(evt);
            }
        });

        btnResultados.setText("RESULTADOS");
        btnResultados.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnResultadosActionPerformed(evt);
            }
        });

        txaBotones.setColumns(20);
        txaBotones.setFont(new java.awt.Font("Segoe UI Emoji", 1, 12)); // NOI18N
        txaBotones.setRows(5);
        jScrollPane4.setViewportView(txaBotones);

        javax.swing.GroupLayout bgLayout = new javax.swing.GroupLayout(bg);
        bg.setLayout(bgLayout);
        bgLayout.setHorizontalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(49, 49, 49)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 360, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 47, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(33, 33, 33)
                                .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(48, 48, 48)
                                .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 101, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(29, 29, 29)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(bgLayout.createSequentialGroup()
                                .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 111, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(28, 28, 28)
                                .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, 114, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(bgLayout.createSequentialGroup()
                                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                                        .addComponent(btnProfundidad, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnNumeroHojas, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addComponent(btnResultados, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                                    .addComponent(btnSumar, javax.swing.GroupLayout.PREFERRED_SIZE, 117, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(jScrollPane4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(10, 10, 10)))))
                .addContainerGap(25, Short.MAX_VALUE))
        );
        bgLayout.setVerticalGroup(
            bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(bgLayout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addComponent(jLabel1)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(34, 34, 34)
                        .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(jLabel2)
                            .addComponent(txtValor, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(bgLayout.createSequentialGroup()
                        .addGap(18, 18, 18)
                        .addComponent(btnAgregar, javax.swing.GroupLayout.PREFERRED_SIZE, 48, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(69, 69, 69)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jScrollPane3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(46, 46, 46)
                .addGroup(bgLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(bgLayout.createSequentialGroup()
                        .addComponent(btnSumar)
                        .addGap(18, 18, 18)
                        .addComponent(btnNumeroHojas)
                        .addGap(25, 25, 25)
                        .addComponent(btnProfundidad)
                        .addGap(18, 18, 18)
                        .addComponent(btnResultados))
                    .addComponent(jScrollPane4))
                .addContainerGap(44, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(bg, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(bg, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAgregarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAgregarActionPerformed
        if(txtValor.getText().trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Ingrese el número","Aviso",2);
            return;
        }
        try{
            entero = Integer.valueOf(txtValor.getText().trim());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Solo se permite el ingreso de numeros enteros","Aviso",2);
            txtValor.setText("");
            return;
        }
        lista.insertar(entero);
        lista.inOrden(enOrden);
        lista.preOrden(preOrden);
        lista.postOrden(postOrden);
        txtValor.setText("");
        txtValor.requestFocus();
    }//GEN-LAST:event_btnAgregarActionPerformed

    private void btnResultadosActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnResultadosActionPerformed
        txaBotones.setText("");
        txaBotones.setText(lista.resultado());
    }//GEN-LAST:event_btnResultadosActionPerformed

    private void btnSumarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSumarActionPerformed
        int suma = lista.sumarValores();
        txaBotones.setText("");
        txaBotones.setText("La suma total es: " + String.valueOf(suma));
    }//GEN-LAST:event_btnSumarActionPerformed

    private void btnNumeroHojasActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnNumeroHojasActionPerformed
        int nHojas = lista.contarHojas();
        txaBotones.setText("");
        txaBotones.setText("La cantidad de hojas en el arbol es: " + String.valueOf(nHojas));
        
    }//GEN-LAST:event_btnNumeroHojasActionPerformed

    private void btnProfundidadActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnProfundidadActionPerformed
        String numero =JOptionPane.showInputDialog(null, "Ingrese numero para hallar profundidad","AVISO",1);
        if(numero == null)   
            return;
        if(numero.trim().isEmpty()){
            JOptionPane.showMessageDialog(null, "Ingrese numero","Aviso",2);
            return;
        }
        
        try{
            entero = Integer.valueOf(numero.trim());
        }catch(NumberFormatException e){
            JOptionPane.showMessageDialog(null, "Solo se acepta un numero entero", "Aviso", 1);
            txtValor.setText("");
            return;
        }

        if(lista.buscar(entero)!= null){
                int profundidad = lista.obtenerProfundidad(entero);
                txaBotones.setText("");
                txaBotones.setText("La profundidad de nodo "+ entero + " es: " + String.valueOf(profundidad));
        }
        else
            JOptionPane.showMessageDialog(null, "El numero ingresado no se encuentra en el arbol","Aviso",2 );
    }//GEN-LAST:event_btnProfundidadActionPerformed

    /**
     * @param args the command line arguments
     */
   

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel bg;
    private javax.swing.JButton btnAgregar;
    private javax.swing.JButton btnNumeroHojas;
    private javax.swing.JButton btnProfundidad;
    private javax.swing.JButton btnResultados;
    private javax.swing.JButton btnSumar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JList<String> lstEnorden;
    private javax.swing.JList<String> lstPostorden;
    private javax.swing.JList<String> lstPreorden;
    private javax.swing.JTextArea txaBotones;
    private javax.swing.JTextField txtValor;
    // End of variables declaration//GEN-END:variables
    private Integer entero;
}
